apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        ports:
        - containerPort: 8096
        env:
        - name: JELLYFIN_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jellyfin-creds
              key: admin_password
        volumeMounts:
        - name: config
          mountPath: /config
        - name: jellyfin-config
          mountPath: /config/system.xml
          subPath: system.xml
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: jellyfin-config
        configMap:
          name: jellyfin-config
      - name: media
        persistentVolumeClaim:
          claimName: media-storage
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  type: LoadBalancer
  ports:
  - port: 8096
    targetPort: 8096
  selector:
    app: jellyfin
