apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: sonarr-creds
              key: api_key
        volumeMounts:
        - name: config
          mountPath: /config
        - name: sonarr-config
          mountPath: /config/config.xml
          subPath: config.xml
        - name: media
          mountPath: /tv
          subPath: tv
        - name: media
          mountPath: /downloads
          subPath: downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: sonarr-config
        configMap:
          name: sonarr-config
      - name: media
        persistentVolumeClaim:
          claimName: media-storage
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  type: LoadBalancer
  ports:
  - port: 8989
    targetPort: 8989
  selector:
    app: sonarr
