apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-creds
  namespace: media
type: Opaque
stringData:
  username: admin
  password: yourSecurePassword123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: media
data:
  qBittorrent.conf: |
    [AutoRun]
    enabled=false

    [BitTorrent]
    Session\DefaultSavePath=/downloads/completed
    Session\TempPath=/downloads/incomplete
    Session\Port=6881

    [Preferences]
    WebUI\Address=0.0.0.0
    WebUI\Port=8080
    WebUI\Username_PBKDF2="@ByteArray(admin)"
    Downloads\SavePath=/downloads/completed
    Downloads\TempPath=/downloads/incomplete